[project]
name = "cubemania-data-vault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.4.0",
    "pandas>=2.0.0",
    "webdriver-manager>=4.0.0",
    "openpyxl>=3.1.0",
    "streamlit>=1.30.0",
]
